(function(g){var window=this;var FCa=function(a,b){return g.Xb(a,b)},i6=function(a){g.Pm(a,"zx",g.yb());
return a},j6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Sm(a.o,b,c)},GCa=function(a,b){var c=[];
g.Dk(b,function(a){try{var b=g.oD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.v(b)?g.nD(b)&&c.push(a):c.push(a)},a);
return c},HCa=function(a,b){var c=GCa(a,b);
(0,g.C)(c,function(a){g.oD.prototype.remove.call(this,a)},a)},ICa=function(a){if(a.Fd){if(a.Fd.locationOverrideToken)return{locationOverrideToken:a.Fd.locationOverrideToken};
if(null!=a.Fd.latitudeE7&&null!=a.Fd.longitudeE7)return{latitudeE7:a.Fd.latitudeE7,longitudeE7:a.Fd.longitudeE7}}return null},JCa=function(a,b,c,d){var e=new g.Gm(null,void 0);
a&&g.Hm(e,a);b&&g.Im(e,b);c&&g.Jm(e,c);d&&g.Km(e,d);return e},KCa=function(a){g.dG[a]&&(a=g.dG[a],(0,g.C)(a,function(a){g.bG[a]&&delete g.bG[a]}),a.length=0)},LCa=function(a){var b=g.aG();
if(b)if(b.clear(a),a)KCa(a);else for(var c in g.dG)KCa(c)},k6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Am;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",MCa(this,a.capabilities||""),NCa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},MCa=function(a,b){a.capabilities.clear();
(0,g.Sd)(b.split(","),g.Fa(FCa,OCa)).forEach(function(b){a.capabilities.add(b)})},NCa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},l6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},m6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},PCa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},QCa=function(a){return new l6(a)},RCa=function(a){return g.za(a)?(0,g.I)(a,QCa):[]},n6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},o6=function(a){return g.za(a)?"["+(0,g.I)(a,n6).join(",")+"]":"null"},p6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},SCa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},q6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},r6=function(a,b){return g.La(a,function(a){return m6(a,b)})},TCa=function(){var a=(0,g.$G)();
a&&HCa(a,a.o.Zd(!0))},s6=function(){var a=g.cH("yt-remote-connected-devices")||[];
g.gb(a);return a},UCa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},VCa=function(a){g.bH("yt-remote-connected-devices",a,86400)},u6=function(){if(t6)return t6;
var a=g.cH("yt-remote-device-id");a||(a=p6(),g.bH("yt-remote-device-id",a,31536E3));for(var b=s6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return t6=d},v6=function(){var a=s6(),b=u6();
g.Pa(a,b);g.eH()&&g.kb(a,b);a=UCa(a);if(g.Qa(a))try{g.MG("remote_sid")}catch(c){}else try{g.LG("remote_sid",a.join(","),-1)}catch(c){}},WCa=function(){return g.cH("yt-remote-session-browser-channel")},XCa=function(){return g.cH("yt-remote-local-screens")||[]},YCa=function(){g.bH("yt-remote-lounge-token-expiration",!0,86400)},ZCa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(XCa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.om)(c,function(a){return!g.Pa(b,a)})&&YCa();
g.bH("yt-remote-local-screens",a,31536E3)},$Ca=function(a,b){g.bH("yt-remote-session-browser-channel",a);
g.bH("yt-remote-session-screen-id",b);var c=s6(),d=u6();g.Pa(c,d)||c.push(d);VCa(c);v6()},w6=function(a){a||(g.dH("yt-remote-session-screen-id"),g.dH("yt-remote-session-video-id"));
v6();a=s6();g.Va(a,u6());VCa(a)},aDa=function(){if(!x6){var a=g.zD();
a&&(x6=new g.iD(a))}return x6?!!x6.get("yt-remote-use-staging-server"):!1},bDa=function(){var a=window.document.createElement("a");
g.gd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},cDa=function(a,b){var c=g.Ld("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.hd(c,g.je("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},dDa=function(){var a=bDa(),b=window.document.getElementById(a),c=b&&g.lF(b,"loaded");
c||b&&!c||(b=cDa(a,function(){g.lF(b,"loaded")||(g.kF(b,"loaded","true"),g.hG(a),g.hE(g.Fa(LCa,a),0))}))},y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},eDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},z6=function(a){a.length?fDa(a.shift(),function(){z6(a)}):A6()},gDa=function(a){return"chrome-extension://"+a+B6},fDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},C6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},A6=function(){var a=eDa();
a&&a(!1,"No cast extension found")},D6=function(){if(hDa){var a=2,b=eDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;fDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",A6,c)}},iDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(D6(),a({command:"cast.sender.init"}))},jDa=function(){D6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+B6,"//www.gstatic.com/eureka/clank"+B6])},E6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.xd=b;this.D=(0,g.A)(this.MK,this);this.o=!1;this.A=0;this.B=this.Da=null;this.C=[]},F6=function(){},G6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Wm(this);this.A=new g.Ag;this.A.setInterval(250)},lDa=function(a,b,c){a.ak=1;
a.zh=i6(b.clone());a.gj=c;a.D=!0;kDa(a,null)},H6=function(a,b,c,d,e){a.ak=1;
a.zh=i6(b.clone());a.gj=null;a.D=c;e&&(a.ME=!1);kDa(a,d)},kDa=function(a,b){a.Ok=(0,g.G)();
I6(a);a.Zh=a.zh.clone();j6(a.Zh,"t",a.F);a.sn=0;a.Pc=a.o.os(a.o.fn()?b:null);0<a.Xs&&(a.lq=new g.fl((0,g.A)(a.cG,a,a.Pc),a.Xs));a.Y.W(a.Pc,"readystatechange",a.aW);var c=a.Fi?g.ec(a.Fi):{};a.gj?(a.dr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Pc.send(a.Zh,a.dr,a.gj,c)):(a.dr="GET",a.ME&&!g.Hd&&(c.Connection="close"),a.Pc.send(a.Zh,a.dr,null,c));a.o.Ef(1)},oDa=function(a,b,c){for(var d=!0;!a.ri&&a.sn<c.length;){var e=mDa(a,c);
if(e==J6){4==b&&(a.Ah=4,K6(15),d=!1);break}else if(e==nDa){a.Ah=4;K6(16);d=!1;break}else L6(a,e)}4==b&&0==c.length&&(a.Ah=1,K6(17),d=!1);a.Lf=a.Lf&&d;d||(M6(a),N6(a))},mDa=function(a,b){var c=a.sn,d=b.indexOf("\n",c);
if(-1==d)return J6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return nDa;d+=1;if(d+c>b.length)return J6;var e=b.substr(d,c);a.sn=d+c;return e},qDa=function(a,b){a.Ok=(0,g.G)();
I6(a);var c=b?window.location.hostname:"";a.Zh=a.zh.clone();g.Pm(a.Zh,"DOMAIN",c);g.Pm(a.Zh,"t",a.F);try{a.Mf=new window.ActiveXObject("htmlfile")}catch(n){M6(a);a.Ah=7;K6(22);N6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in O6)k=O6[l];else if(l in pDa)k=O6[l]=pDa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=O6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.id(g.Bc("b/12014412"),d+"</body></html>");a.Mf.open();a.Mf.write(g.$c(c));a.Mf.close();a.Mf.parentWindow.m=(0,g.A)(a.iV,a);a.Mf.parentWindow.d=(0,g.A)(a.VD,a,!0);a.Mf.parentWindow.rpcClose=(0,g.A)(a.VD,a,!1);c=a.Mf.createElement("DIV");a.Mf.parentWindow.document.body.appendChild(c);d=g.Pc(a.Zh.toString());d=g.sb(g.Mc(d));d=g.id(g.Bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,g.$c(d));a.o.Ef(1)},
I6=function(a){a.Kw=(0,g.G)()+a.C;
rDa(a,a.C)},rDa=function(a,b){if(null!=a.il)throw Error("WatchDog timer not null");
a.il=P6((0,g.A)(a.yV,a),b)},Q6=function(a){a.il&&(g.x.clearTimeout(a.il),a.il=null)},N6=function(a){a.o.Yz()||a.ri||a.o.Wp(a)},M6=function(a){Q6(a);
g.jf(a.lq);a.lq=null;a.A.stop();g.bn(a.Y);if(a.Pc){var b=a.Pc;a.Pc=null;b.abort();b.dispose()}a.Mf&&(a.Mf=null)},L6=function(a,b){try{a.o.ND(a,b),a.o.Ef(4)}catch(c){}},tDa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;sDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){tDa(a,b,c,d,f)},f)})}},sDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{R6(d),c(!0)}catch(e){}};
d.onerror=function(){try{R6(d),c(!1)}catch(e){}};
d.onabort=function(){try{R6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{R6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},R6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},uDa=function(a){this.o=a;
this.A=new F6},vDa=function(a){var b=S6(a.o,a.rl,"/mail/images/cleardot.gif");
i6(b);tDa(b.toString(),5E3,(0,g.A)(a.QJ,a),3,2E3);a.Ef(1)},U6=function(a){var b=a.o.J;
if(null!=b)K6(5),b?(K6(11),T6(a.o,a,!1)):(K6(12),T6(a.o,a,!0));else if(a.Be=new G6(a,void 0,void 0,void 0),a.Be.Fi=a.Vs,b=a.o,b=S6(b,b.fn()?a.Tl:null,a.Ws),K6(5),!g.Fd||g.tc(10))j6(b,"TYPE","xmlhttp"),H6(a.Be,b,!1,a.Tl,!1);else{j6(b,"TYPE","html");var c=a.Be;a=!!a.Tl;c.ak=3;c.zh=i6(b.clone());qDa(c,a)}},V6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new F6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},wDa=function(a,b){this.o=a;
this.map=b;this.context=null},xDa=function(a){g.lf.call(this,"statevent",a)},yDa=function(a,b){g.lf.call(this,"timingevent",a);
this.size=b},zDa=function(a){g.lf.call(this,"serverreachability",a)},CDa=function(a){ADa(a);
if(3==a.o){var b=a.Mm++,c=a.Fo.clone();g.Pm(c,"SID",a.B);g.Pm(c,"RID",b);g.Pm(c,"TYPE","terminate");W6(a,c);b=new G6(a,a.B,b,void 0);b.ak=2;b.zh=i6(c.clone());(new window.Image).src=b.zh;b.Ok=(0,g.G)();I6(b)}BDa(a)},DDa=function(a){a.nK(1,0);
a.Fo=S6(a,null,a.Us);X6(a)},ADa=function(a){a.mh&&(a.mh.abort(),a.mh=null);
a.xc&&(a.xc.cancel(),a.xc=null);a.xg&&(g.x.clearTimeout(a.xg),a.xg=null);Y6(a);a.ee&&(a.ee.cancel(),a.ee=null);a.rh&&(g.x.clearTimeout(a.rh),a.rh=null)},EDa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new wDa(a.VQ++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.ee||a.rh||(a.rh=P6((0,g.A)(a.TD,a),0),a.Pj=0)},GDa=function(a,b){if(1==a.o){if(!b){a.Mm=Math.floor(1E5*Math.random());
var c=a.Mm++,d=new G6(a,"",c,void 0);d.Fi=null;var e=Z6(a),f=a.Fo.clone();g.Pm(f,"RID",c);g.Pm(f,"CVER","1");W6(a,f);lDa(d,f,e);a.ee=d;a.o=2}}else 3==a.o&&(b?FDa(a,b):0==a.A.length||a.ee||FDa(a))},FDa=function(a,b){if(b)if(6<a.ti){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Mm-1;var d=Z6(a)}else c=b.G,d=b.gj;else c=a.Mm++,d=Z6(a);var e=a.Fo.clone();g.Pm(e,"SID",a.B);g.Pm(e,"RID",c);g.Pm(e,"AID",a.pk);W6(a,e);c=new G6(a,a.B,c,a.Pj+1);c.Fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ee=c;lDa(c,e,d)},W6=function(a,b){if(a.wd){var c=a.wd.Ez();
c&&g.Kb(c,function(a,c){g.Pm(b,c,a)})}},Z6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.ti&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.ti?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},HDa=function(a){a.xc||a.xg||(a.G=1,a.xg=P6((0,g.A)(a.SD,a),0),a.Cj=0)},$6=function(a){if(a.xc||a.xg||3<=a.Cj)return!1;
a.G++;a.xg=P6((0,g.A)(a.SD,a),IDa(a,a.Cj));a.Cj++;return!0},T6=function(a,b,c){a.Zq=c;
a.Zf=b.Ig;a.F||DDa(a)},Y6=function(a){null!=a.wi&&(g.x.clearTimeout(a.wi),a.wi=null)},IDa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.wd&&(c=null);var d=(0,g.A)(a.SW,a);c||(c=new g.Gm("//www.google.com/images/cleardot.gif"),i6(c));sDa(c.toString(),1E4,d)}else K6(2);JDa(a,b)},JDa=function(a,b){a.o=0;
a.wd&&a.wd.Dy(b);BDa(a);ADa(a)},BDa=function(a){a.o=0;
a.Zf=-1;if(a.wd)if(0==a.C.length&&0==a.A.length)a.wd.Vr();else{g.Ya(a.C);var b=g.Ya(a.A);a.C.length=0;a.A.length=0;a.wd.Vr(b)}},S6=function(a,b,c){var d=g.Qm(c);
if(""!=d.A)b&&g.Im(d,b+"."+d.A),g.Jm(d,d.D);else{var e=window.location;d=JCa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Dl&&g.Kb(a.Dl,function(a,b){g.Pm(d,b,a)});
g.Pm(d,"VER",a.ti);W6(a,d);return d},P6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},K6=function(a){b7.dispatchEvent(new xDa(b7,a))},KDa=function(){},LDa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.M.call(this);
this.o=new g.ju(this.ZU,0,this);g.N(this,this.o);this.xd=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},d7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.hD;this.A=new c7(this.CX,this);this.o=this.ib=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},MDa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Zq,sessionId:a.o.B,arrayId:a.o.pk}},NDa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&GDa(a.o),CDa(a.o));a.H=0},e7=function(a){return!!a.o&&3==a.o.o},ODa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Qg(a)||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bb(a,"10.0")&&(this.A=!1))},g7=function(a,b){var c=a.o;
if(g.v(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Zg(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Cd:g.Fa(a.D,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.yE(b,a)},SDa=function(){var a=PDa;
QDa();i7.push(a);RDa(i7)},j7=function(a,b){QDa();
var c=i7,d=TDa(a,String(b));g.Qa(c)?UDa(d):(RDa(c),(0,g.C)(c,function(a){a(d)}))},QDa=function(){i7||(i7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",i7,void 0))},UDa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},RDa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},TDa=function(a,b){var c=((0,g.G)()-VDa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.TF.call(this);
this.G=a;this.o=[]},WDa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},XDa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Sd)(a.o,function(a){return!!q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=WDa(a,b[d])||c;return c},YDa=function(a,b){var c=a.o.length;
a.o=(0,g.Sd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},o7=function(a,b,c,d){g.TF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Da=window.NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;p7(this);this.info("Initializing with "+o6(this.o))},ZDa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.ZK,a),(0,g.A)(a.YK,a))}},p7=function(a){var b=RCa(XCa());
b=(0,g.Sd)(b,function(a){return!a.uuid});
return XDa(a,b)},r7=function(a,b){ZCa((0,g.I)(a.o,PCa));
b&&YCa()},t7=function(a,b){g.TF.call(this);
this.F=b;var c=g.cH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;s7("Initialized with "+g.Hg(this.o))},$Da=function(a,b,c){var d=g7(a.D,"/pairing/get_screen_availability");
h7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},u7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.o))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Hg(a.o)),a.o=b,a.V("screenChange"));aEa(a)},v7=function(a){(0,window.isNaN)(a.B)||g.jE(a.B);
a.B=g.hE((0,g.A)(a.Uv,a),0<a.C&&a.C<(0,g.G)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},bEa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},aEa=function(a){a=g.Sb(g.Mb(a.o,function(a){return a}));
g.gb(a);a.length?g.bH("yt-remote-online-screen-ids",a.join(","),60):g.dH("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};cEa(this)},eEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.ue();if(k=(c?r6(k,c):null)||r6(k,b)){k.uuid=b;var l=x7(a,k);$Da(a.A,l,function(a){e(a?l:null)})}else c?dEa(a,c,(0,g.A)(function(a){var f=x7(this,new l6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));$Da(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},fEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},dEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.yE(g7(a.F,"/pairing/get_lounge_token_batch"),e)},gEa=function(a){a.o=a.B.ue();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+o6(a.o))},cEa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.mL,a));gEa(a);a.C=RCa(g.cH("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+o6(a.C));a.A=new t7(a.F,(0,g.A)(a.ue,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=r6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.bH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,PCa)));y7(a);a.D[b.uuid]=b.id;g.bH("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.cH("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.TF.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},A7=function(a,b){j7(a.M,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.IX,this);this.D=(0,g.A)(this.LV,this);this.C=g.hE((0,g.A)(function(){hEa(this,null)},this),12E4)},iEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Hg(b))},hEa=function(a,b){g.jE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Xp,a),d=(0,g.A)(a.Ae,a);a.Oz(b,c,d,5)}}else a.Ae(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.A)(this.LX,this);this.o=g.z},jEa=function(a){a.o=a.J.jG(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.Xp(a)},a),(0,g.A)(function(a){this.o=g.z;
this.Ae(a)},a))},kEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}aDa()&&(b.env_useStageMdx=1);return g.Xg(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.o=g.hE((0,g.A)(this.rk,this,null),150)},E7=function(a,b,c,d){g.TF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.lU,this)},lEa=function(a,b){return b?g.La(a.B,function(a){return m6(b,a.label)},a):null},F7=function(a){j7("Controller",a)},PDa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},G7=function(a){return a.D||!!a.B.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.jf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.QD,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.rk(null)):a.V("yt-remote-cast2-session-change",null))},mEa=function(a){var b=a.A.iG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&m6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=lEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},sEa=function(a,b,c,d,e,f,k){nEa()?oEa(b,e,f,k)&&(J7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?pEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?pEa(a,c):(K7("Failed to load cast API: "+d),L7(!1),J7(!1),g.dH("yt-remote-cast-available"),g.dH("yt-remote-cast-receiver"),qEa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):dDa():C6("CriOS")?iDa():C6("Android")&&C6("Chrome/")&&window.navigator.presentation?jDa():window.chrome&&window.navigator.presentation&&!C6("Edge")?(D6(),z6(rEa.map(gDa))):A6())):I7("Cannot initialize because not running Chrome")},qEa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);tEa(!1);g.fG(N7);N7.length=0},O7=function(){return!!g.cH("yt-remote-cast-installed")},uEa=function(){var a=g.cH("yt-remote-cast-receiver");
return a?a.friendlyName:null},vEa=function(){I7("clearCurrentReceiver");
g.dH("yt-remote-cast-receiver")},wEa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.eG("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},nEa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.tI||a},xEa=function(a,b){M7().init(a,b)},oEa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.bH("yt-remote-cast-available",a);g.iG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){I7("onReceiverSelected: "+a.friendlyName);
g.bH("yt-remote-cast-receiver",a);g.iG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){I7("onReceiverResumed: "+a.friendlyName);
g.bH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){I7("onSessionChange: "+n6(a));
a||g.dH("yt-remote-cast-receiver");g.iG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},pEa=function(a,b){L7(!0);
J7(!1);xEa(a,function(a){a?(tEa(!0),g.hG("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.dH("yt-remote-cast-available"),g.dH("yt-remote-cast-receiver"),qEa());b(a)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.bH("yt-remote-cast-installed",a)},P7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},tEa=function(a){I7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.eg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.eg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.G)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},U7=function(a){return a.rb()?((0,g.G)()-a.G)/1E3:0},V7=function(a,b){a.H=b;
a.G=(0,g.G)()},W7=function(a){switch(a.o){case 1:case 1081:return((0,g.G)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.fc(a.A);b.hasPrevious=a.eg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},$7=function(a,b){g.TF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.xC;this.B=this.A=null;this.J=(0,g.A)(this.FR,this);this.G=(0,g.A)(this.Pm,this);this.H=(0,g.A)(this.ER,this);this.K=(0,g.A)(this.RR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Rw,this),yEa(this))):c=3;0!=c&&(b?this.Rw(c):g.hE((0,g.A)(function(){this.Rw(c)},this),0));
var d=wEa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},a8=function(a){return new S7(a.C.getPlayerContextData())},yEa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.gU,a),this))},a)},zEa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},b8=function(a,b){50>a.D.yc()&&g.zC(a.D,b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.o&&(d.o=b);c8(a,d)},e8=function(a,b,c){a.C.sendMessage(b,c)},c8=function(a,b){zEa(a);
a.C.setPlayerContextData(Y7(b));yEa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Pm(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Pm(a.B.media[0]))},AEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;V7(d,a.A.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.A)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.TF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.T=[];this.C=this.G=this.B=this.jb=this.o=null;this.sa=a;this.T.push(g.CF(window,"beforeunload",(0,g.A)(this.QK,this)));this.A=[];this.jb=new S7;this.aa=b.id;this.o=BEa(this,c);this.o.subscribe("handlerOpened",this.JR,this);this.o.subscribe("handlerClosed",this.GR,this);this.o.subscribe("handlerError",this.HR,this);this.o.subscribe("handlerMessage",this.IR,this);ODa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.jb.videoId;g.eH()&&g.bH("yt-remote-session-video-id",a)},this)},h8=function(a){j7("conn",a)},BEa=function(a,b){return new d7(g7(a.sa,"/bc"),b)},i8=function(a,b){a.V("proxyStateChange",b)},CEa=function(a){a.D=g.hE((0,g.A)(function(){h8("Connecting timeout");
this.F(1)},a),2E4)},j8=function(a){g.jE(a.D);
a.D=window.NaN},k8=function(a){g.jE(a.M);
a.M=window.NaN},DEa=function(a){l8(a);
a.L=g.hE((0,g.A)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.jE(a.L);
a.L=window.NaN},FEa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&(0,window.isNaN)(a.D))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.Z()&&a.jb.reset(),i8(a,1),m8(a,"getNowPlaying"),EEa(a)):a.F(1)},GEa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.$b(b.params)?a.jb.A=null:a.jb.A=b.params,a.V("remotePlayerChange"))},HEa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;X7(a.jb,c,d);a.V("remoteQueueChange")},JEa=function(a,b){b.params=b.params||{};
HEa(a,b);IEa(a,b);a.V("autoplayDismissed")},IEa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
V7(a.jb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.jb.o&&(c=-1E3);a.jb.o=c;c=Number(b.params.loadedTime);a.jb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.jb.J=(0,window.isNaN)(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.jb.o?DEa(a):l8(a);
a.V("remotePlayerChange")},KEa=function(a,b){if(-1E3!=a.jb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);V7(a.jb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},LEa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=(0,window.parseInt)(b.params.volume,10);a.jb.muted=c;a.V("remotePlayerChange")},MEa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},NEa=function(a,b){var c="true"==b.params.hasNext;
a.jb.eg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.V("previousNextChange")},EEa=function(a){g.jE(a.K);
a.K=g.hE((0,g.A)(a.F,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Hg(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.hd=a;this.A=[];this.A.push(this.hd.$_s("screenChange",(0,g.A)(this.GX,this)));this.A.push(this.hd.$_s("onlineScreenChange",(0,g.A)(this.DT,this)))},SEa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.bE("MDX_CONFIG")||b;TCa();v6();o8||(o8=new f7(b?b.loungeApiHost:void 0),aDa()&&(o8.o="/api/loungedev"));p8||(p8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",p8,void 0));OEa();var c=q8();if(!c){var d=new w7(o8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);sEa(a,d,function(a){a?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.iG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Hg(b)),t8.push(g.eG("yt-remote-cast2-availability-change",function(){g.iG("yt-remote-receiver-availability-change")})),t8.push(g.eG("yt-remote-cast2-receiver-selected",function(){u8(null);
g.iG("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.eG("yt-remote-cast2-receiver-resumed",function(){g.iG("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.eG("yt-remote-cast2-session-change",PEa)),t8.push(g.eG("yt-remote-connection-change",function(a){a?R7(r8(),"YouTube TV"):v8()||(R7(null,null),vEa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.ZF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),s8(" -- with channel params: "+
g.Hg(a)),QEa(a),c.start(),r8()||REa())},UEa=function(){var a=TEa();
O7()&&g.cH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},TEa=function(){var a=q8().hd.$_gos();
var b=x8();b&&y8()&&(q6(a,b)||a.push(b));return SCa(a)},z8=function(){var a=VEa();
!a&&O7()&&uEa()&&(a={key:"cast-selector-receiver",name:uEa()});return a},VEa=function(){var a=TEa(),b=x8();
b||(b=v8());return g.La(a,function(a){return b&&m6(b,a.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().ue();return r6(b,a)},PEa=function(a){s8("remote.onCastSessionChange_: "+n6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.y("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.y("yt.mdx.remote.currentScreenId_")},WEa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},XEa=function(){return g.y("yt.mdx.remote.connectData_")},u8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.y("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||WEa("");g.ua("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.C)(p8,function(b){b(a)}),p8.length=0);
b&&!a?g.iG("yt-remote-connection-change",!1):!b&&a&&g.iG("yt-remote-connection-change",!0)},v8=function(){var a=g.eH();
if(!a)return null;var b=q8().ue();return r6(b,a)},B8=function(a,b){x8()&&x8();
WEa(a.id);var c=new g8(o8,a,w8());c.connect(b,XEa());c.subscribe("beforeDisconnect",function(a){g.iG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){y8()&&C8(null)});
C8(c)},REa=function(){var a=v8();
a?(s8("Resume connection to: "+n6(a)),B8(a,0)):(w6(),vEa(),s8("Skipping connecting because no session screen found."))},OEa=function(){var a=w8();
if(g.$b(a)){a=u6();var b=g.cH("yt-remote-session-name")||"",c=g.cH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},QEa=function(a){a?(g.bH("yt-remote-session-app",a.app),g.bH("yt-remote-session-name",a.name)):(g.dH("yt-remote-session-app"),g.dH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.M.call(this);
this.H=a;this.A=b;this.B=new g.QF(this);g.N(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.YS);this.B.R(b,"captionschanged",this.DR);this.B.R(b,"captionssettingschanged",this.vF);this.B.R(b,"videoplayerreset",this.Yp);this.B.R(b,"mdxautoplaycancel",this.PJ);this.T=this.B.R(b,"onVolumeChange",this.xD);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.MD,this);c.subscribe("remotePlayerChange",this.Sm,this);c.subscribe("remoteQueueChange",this.Yp,this);c.subscribe("autoplayUpNext",this.iD,
this);c.subscribe("previousNextChange",this.JD,this);c.subscribe("nowAutoplaying",this.AD,this);c.subscribe("autoplayDismissed",this.hD,this);this.suggestion=null;this.J=new g.GP(64);this.C=new g.ju(this.rF,500,this);g.N(this,this.C);this.D=new g.ju(this.sF,1E3,this);g.N(this,this.D);this.L=new E6(this.hX,0,this);g.N(this,this.L);this.F={};this.M=new g.ju(this.RF,1E3,this);g.N(this,this.M);this.K=new g.fl(this.IP,1E3,this);g.N(this,this.K);this.O=g.z;this.vF();this.Yp();this.Sm()},G8=function(a,b){var c=
a.H,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.o.V("progresssync",b,d)},YEa=function(a){G8(a,0);
a.C.stop();H8(a,new g.GP(64))},J8=function(a,b){if(I8(a)&&!a.G){var c=null;
b&&(c={style:a.A.Zi()},g.hc(c,b));a.o.gF(a.A.getVideoData(1).videoId,c);a.F=a8(a.o).A}},K8=function(a,b){var c=a.A.lg();
if(c){var d=c.se();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.jk;f=ICa(f);var n=a8(c);l=l||0;var p={videoId:k,currentIndex:l};X7(n,k,l);g.v(b)&&(V7(n,b),p.currentTime=b);g.v(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Hg(f));e8(c,"setPlaylist",p);e||c8(c,n);H8(a,new g.GP(1))},ZEa=function(a,b){if(b){var c=a.A.Bc("captions","tracklist",{IA:1});
c&&c.length?(a.A.Rd("captions","track",b),a.G=!1):(a.A.yk("captions"),a.G=!0)}else a.A.Rd("captions","track",{})},I8=function(a){return a8(a.o).videoId==a.A.getVideoData(1).videoId},H8=function(a,b){a.D.stop();
var c=a.J;if(!g.LP(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.iU(a.A,d);a.J=b;$Ea(a.H,c,b)}},L8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.lqa()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.fV(this,250);g.N(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);aFa(this,g.fU(a))},aFa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Bc("remote","currentReceiver").name};
c=g.X(b,128)?g.f0("Error on $RECEIVER_NAME",c):b.rb()||g.X(b,4)?g.f0("Playing on $RECEIVER_NAME",c):g.f0("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},M8=function(a,b){g.CY.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},N8=function(a){g.GU.call(this,a);
this.B={key:p6(),name:"This computer"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.GP(64);this.J=0;if(!g.TM(g.Y(this.o))){a=this.o;var b=g.UH(a);b&&(b=b.sm())&&(b=new M8(a,b),g.N(this,b));b=new L8(a);g.N(this,b);g.yU(a,b.element,4)}},$Ea=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.QP(c,b))},O8=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)A8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.lg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.jk,index:Math.max(a.o.MB(),0),currentTime:0==f?void 0:f};(d=ICa(d))&&(c.locationInfo=d);d=c}else d=null;s8("Connecting to: "+g.Hg(b));"cast-selector-receiver"==b.key?(u8(d||null),P7()?M7().setLaunchParams(d||null):
K7("setLaunchParams called before ready.")):!d&&D8()&&r8()==b.key?g.iG("yt-remote-connection-change",!0):(A8(),u8(d||null),d=q8().ue(),(d=r6(d,b.key))&&B8(d,1))}},pDa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},O6={"'":"\\'"},bFa={},OCa={VY:"atp",B3:"ska",Q2:"que",Z1:"mus",x3:"sus",d0:"dsp"};
k6.prototype.no=function(){var a=new k6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var x6,t6="",B6=y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",hDa=y6("loadCastFramework")||y6("loadCastApplicationFramework"),rEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(E6,g.M);g.h=E6.prototype;g.h.LK=function(a){this.C=arguments;this.o=!1;this.Da?this.B=(0,g.G)()+this.xd:this.Da=g.Bg(this.D,this.xd)};
g.h.stop=function(){this.Da&&(g.Cg(this.Da),this.Da=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();E6.fa.X.call(this)};
g.h.MK=function(){this.B?(this.Da=g.Bg(this.D,this.B-(0,g.G)()),this.B=null):(this.Da=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};F6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
F6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=G6.prototype;g.h.Fi=null;g.h.Lf=!1;g.h.il=null;g.h.Kw=null;g.h.Ok=null;g.h.ak=null;g.h.zh=null;g.h.Zh=null;g.h.gj=null;g.h.Pc=null;g.h.sn=0;g.h.Mf=null;g.h.dr=null;g.h.Ah=null;g.h.Ul=-1;g.h.ME=!0;g.h.ri=!1;g.h.Xs=0;g.h.lq=null;var nDa={},J6={};g.h=G6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.aW=function(a){a=a.target;var b=this.lq;b&&3==g.tx(a)?b.Ql():this.cG(a)};
g.h.cG=function(a){try{if(a==this.Pc)a:{var b=g.tx(this.Pc),c=this.Pc.A,d=this.Pc.getStatus();if(g.Fd&&!g.tc(10)||g.Hd&&!g.sc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.nf&&!g.xx(this.Pc))break a;this.ri||4!=b||7==c||(8==c||0>=d?this.o.Ef(3):this.o.Ef(2));Q6(this);var e=this.Pc.getStatus();this.Ul=e;var f=g.xx(this.Pc);(this.Lf=200==e)?(4==b&&M6(this),this.D?(oDa(this,b,f),g.nf&&this.Lf&&3==b&&(this.Y.W(this.A,"tick",this.WV),this.A.start())):L6(this,f),this.Lf&&!this.ri&&(4==b?this.o.Wp(this):
(this.Lf=!1,I6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ah=3,K6(13)):(this.Ah=0,K6(14)),M6(this),N6(this))}}catch(k){this.Pc&&g.xx(this.Pc)}finally{}};
g.h.WV=function(){var a=g.tx(this.Pc),b=g.xx(this.Pc);this.sn<b.length&&(Q6(this),oDa(this,a,b),this.Lf&&4!=a&&I6(this))};
g.h.iV=function(a){P6((0,g.A)(this.hV,this,a),0)};
g.h.hV=function(a){this.ri||(Q6(this),L6(this,a),I6(this))};
g.h.VD=function(a){P6((0,g.A)(this.gV,this,a),0)};
g.h.gV=function(a){this.ri||(M6(this),this.Lf=a,this.o.Wp(this),this.o.Ef(4))};
g.h.cancel=function(){this.ri=!0;M6(this)};
g.h.yV=function(){this.il=null;var a=(0,g.G)();0<=a-this.Kw?(2!=this.ak&&this.o.Ef(3),M6(this),this.Ah=2,K6(18),N6(this)):rDa(this,this.Kw-a)};g.h=uDa.prototype;g.h.Vs=null;g.h.Be=null;g.h.mq=!1;g.h.Zz=null;g.h.Bo=null;g.h.du=null;g.h.Ws=null;g.h.Xe=null;g.h.Ig=-1;g.h.Tl=null;g.h.rl=null;g.h.connect=function(a){this.Ws=a;a=S6(this.o,null,this.Ws);K6(3);this.Zz=(0,g.G)();var b=this.o.H;null!=b?(this.Tl=b[0],(this.rl=b[1])?(this.Xe=1,vDa(this)):(this.Xe=2,U6(this))):(j6(a,"MODE","init"),this.Be=new G6(this,void 0,void 0,void 0),this.Be.Fi=this.Vs,H6(this.Be,a,!1,null,!0),this.Xe=0)};
g.h.QJ=function(a){if(a)this.Xe=2,U6(this);else{K6(4);var b=this.o;b.Zf=b.mh.Ig;a7(b,9)}a&&this.Ef(2)};
g.h.os=function(a){return this.o.os(a)};
g.h.abort=function(){this.Be&&(this.Be.cancel(),this.Be=null);this.Ig=-1};
g.h.Yz=function(){return!1};
g.h.ND=function(a,b){this.Ig=a.Ul;if(0==this.Xe)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Zf=this.Ig;a7(c,2);return}this.Tl=c[0];this.rl=c[1]}else c=this.o,c.Zf=this.Ig,a7(c,2);else if(2==this.Xe)if(this.mq)K6(7),this.du=(0,g.G)();else if("11111"==b){if(K6(6),this.mq=!0,this.Bo=(0,g.G)(),c=this.Bo-this.Zz,!g.Fd||g.tc(10)||500>c)this.Ig=200,this.Be.cancel(),K6(12),T6(this.o,this,!0)}else K6(8),this.Bo=this.du=(0,g.G)(),this.mq=!1};
g.h.Wp=function(){this.Ig=this.Be.Ul;if(this.Be.Lf)0==this.Xe?this.rl?(this.Xe=1,vDa(this)):(this.Xe=2,U6(this)):2==this.Xe&&((!g.Fd||g.tc(10)?!this.mq:200>this.du-this.Bo)?(K6(11),T6(this.o,this,!1)):(K6(12),T6(this.o,this,!0)));else{0==this.Xe?K6(9):2==this.Xe&&K6(10);var a=this.o;a.Zf=this.Ig;a7(a,2)}};
g.h.fn=function(){return this.o.fn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Ef=function(a){this.o.Ef(a)};g.h=V6.prototype;g.h.Dl=null;g.h.ee=null;g.h.xc=null;g.h.Us=null;g.h.Fo=null;g.h.ry=null;g.h.So=null;g.h.Mm=0;g.h.VQ=0;g.h.wd=null;g.h.rh=null;g.h.xg=null;g.h.wi=null;g.h.mh=null;g.h.Zq=null;g.h.pk=-1;g.h.YA=-1;g.h.Zf=-1;g.h.Pj=0;g.h.Cj=0;g.h.ti=8;var b7=new g.Mf;g.B(xDa,g.lf);g.B(yDa,g.lf);g.B(zDa,g.lf);g.h=V6.prototype;g.h.connect=function(a,b,c,d,e){K6(0);this.Us=b;this.Dl=c||{};d&&g.v(e)&&(this.Dl.OSID=d,this.Dl.OAID=e);this.F?(P6((0,g.A)(this.Oy,this,a),100),DDa(this)):this.Oy(a)};
g.h.Oy=function(a){this.mh=new uDa(this);this.mh.Vs=null;this.mh.A=this.D;this.mh.connect(a)};
g.h.Yz=function(){return 0==this.o};
g.h.TD=function(a){this.rh=null;GDa(this,a)};
g.h.SD=function(){this.xg=null;this.xc=new G6(this,this.B,"rpc",this.G);this.xc.Fi=null;this.xc.Xs=0;var a=this.ry.clone();g.Pm(a,"RID","rpc");g.Pm(a,"SID",this.B);g.Pm(a,"CI",this.Zq?"0":"1");g.Pm(a,"AID",this.pk);W6(this,a);if(!g.Fd||g.tc(10))g.Pm(a,"TYPE","xmlhttp"),H6(this.xc,a,!0,this.So,!1);else{g.Pm(a,"TYPE","html");var b=this.xc,c=!!this.So;b.ak=3;b.zh=i6(a.clone());qDa(b,c)}};
g.h.ND=function(a,b){if(0!=this.o&&(this.xc==a||this.ee==a))if(this.Zf=a.Ul,this.ee==a&&3==this.o)if(7<this.ti){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.xg){if(this.xc)if(this.xc.Ok+3E3<this.ee.Ok)Y6(this),this.xc.cancel(),this.xc=null;else break a;$6(this);K6(19)}}else this.YA=c[1],0<this.YA-this.pk&&37500>c[2]&&this.Zq&&0==this.Cj&&!this.wi&&(this.wi=P6((0,g.A)(this.xR,this),6E3));else a7(this,11)}else b!=bFa.YZ.o&&a7(this,11);else if(this.xc==a&&
Y6(this),!g.D(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.pk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.So=e[2],e=e[3],null!=e?this.ti=e:this.ti=6,this.o=3,this.wd&&this.wd.Fy(),this.ry=S6(this,this.fn()?this.So:null,this.Us),HDa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.wd&&this.wd.Ey(e),this.Cj=0)}}};
g.h.xR=function(){null!=this.wi&&(this.wi=null,this.xc.cancel(),this.xc=null,$6(this),K6(20))};
g.h.Wp=function(a){if(this.xc==a){Y6(this);this.xc=null;var b=2}else if(this.ee==a)this.ee=null,b=1;else return;this.Zf=a.Ul;if(0!=this.o)if(a.Lf)1==b?(b=(0,g.G)()-a.Ok,b7.dispatchEvent(new yDa(b7,a.gj?a.gj.length:0,b,this.Pj)),X6(this),this.C.length=0):HDa(this);else{var c=a.Ah,d;if(!(d=3==c||7==c||0==c&&0<this.Zf)){if(d=1==b)this.ee||this.rh||1==this.o||2<=this.Pj?d=!1:(this.rh=P6((0,g.A)(this.TD,this,a),IDa(this,this.Pj)),this.Pj++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,5);
break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.h.nK=function(a){if(!g.Pa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.SW=function(a){a?K6(2):(K6(1),JDa(this,8))};
g.h.os=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.nx;a.H=!1;return a};
g.h.isActive=function(){return!!this.wd&&this.wd.isActive(this)};
g.h.Ef=function(a){b7.dispatchEvent(new zDa(b7,a))};
g.h.fn=function(){return!(!g.Fd||g.tc(10))};
g.h=KDa.prototype;g.h.Fy=function(){};
g.h.Ey=function(){};
g.h.Dy=function(){};
g.h.Vr=function(){};
g.h.Ez=function(){return{}};
g.h.isActive=function(){return!0};g.B(c7,g.M);g.h=c7.prototype;g.h.ZU=function(){this.xd=Math.min(3E5,2*this.xd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.xd+15E3*Math.random();g.ku(this.o,a);this.A=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.xd=5E3};g.B(d7,KDa);g.h=d7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Xd=function(a){return this.B.Xd(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.jf(this.B),NDa(this),g.jf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.wd=null);d.wd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.pk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.hc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&EDa(this.o,c)};
g.h.Fy=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)EDa(this.o,a[b])}this.V("handlerOpened")};
g.h.Dy=function(a){var b=2==a&&401==this.o.Zf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Vr=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.Ez=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.hc(a,this.D);return a};
g.h.Ey=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),CDa(this.o)):this.V("handlerMessage",new LDa(a[0],a[1]))};
g.h.CX=function(){this.A.isActive();var a=this.o,b=0;a.xc&&b++;a.ee&&b++;0!=b||this.connect(this.D,this.C)};f7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.D=function(a){a(Error("request timed out"))};var VDa=(0,g.G)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.B(n7,g.TF);n7.prototype.ue=function(){return this.o};
n7.prototype.contains=function(a){return!!q6(this.o,a)};
n7.prototype.get=function(a){return a?r6(this.o,a):null};
n7.prototype.info=function(a){j7(this.G,a)};g.B(o7,g.TF);var cFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=o7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Da)&&this.hG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Da)||(g.jE(this.Da),this.Da=window.NaN)};
g.h.X=function(){this.stop();o7.fa.X.call(this)};
g.h.hG=function(){this.Da=window.NaN;this.o=g.yE(g7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.EX,this),onError:(0,g.A)(this.DX,this),Cd:(0,g.A)(this.FX,this)})};
g.h.EX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new l6(c))};
g.h.DX=function(a){this.o=null;a.status&&404==a.status?this.A>=cFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=cFa[this.A],this.Da=g.hE((0,g.A)(this.hG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.FX=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(q7,n7);g.h=q7.prototype;g.h.start=function(){p7(this)&&this.V("screenChange");!g.cH("yt-remote-lounge-token-expiration")&&ZDa(this);g.jE(this.A);this.A=g.hE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){p7(this);WDa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||ZDa(this)};
g.h.remove=function(a,b){var c=p7(this);YDa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Uq=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.jE(this.A);q7.fa.X.call(this)};
g.h.ZK=function(a){p7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.G,"Missed "+b+" lounge tokens.")};
g.h.YK=function(a){j7(this.G,"Requesting lounge tokens failed: "+a)};g.B(t7,g.TF);g.h=t7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.cH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.G)()-144E5<a?0:a)?v7(this):(this.C=(0,g.G)()+3E5,g.bH("yt-remote-fast-check-period",this.C),this.Uv())};
g.h.isEmpty=function(){return g.$b(this.o)};
g.h.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Mb(this.o,function(b,d){return b&&!!r6(a,d)},this);
u7(this,b)};
g.h.X=function(){g.jE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);t7.fa.X.call(this)};
g.h.Uv=function(){g.jE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=bEa(this);if(g.Pb(a)){var b=g7(this.D,"/pairing/get_screen_availability");this.A=h7(this.D,b,{lounge_token:g.Sb(a).join(",")},(0,g.A)(this.GU,this,a),(0,g.A)(this.FU,this))}else u7(this,{}),v7(this)};
g.h.GU=function(a,b){this.A=null;var c=g.Sb(bEa(this));if(g.ib(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.gc("Changing Screen set during request."),this.Uv()};
g.h.FU=function(a){this.gc("Screen availability failed: "+a);this.A=null;v7(this)};
g.h.gc=function(a){j7("OnlineScreenService",a)};g.B(w7,n7);g.h=w7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Uq=function(a,b,c,d){this.B.contains(a)?this.B.Uq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.G,a),d(Error(a)))};
g.h.ue=function(a){return a?this.o:g.Xa(this.o,(0,g.Sd)(this.C,function(a){return!this.contains(a)},this))};
g.h.iG=function(){return(0,g.Sd)(this.ue(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.jG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.jf(f);d(x7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.jf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.HX=function(a,b,c,d){g.yE(g7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new l6(d.screen||{});if(!e.name||fEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);fEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(x7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Cd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.jf(this.B);g.jf(this.A);w7.fa.X.call(this)};
g.h.mL=function(){gEa(this);this.V("screenChange");this.A.update()};
w7.prototype.dispose=w7.prototype.dispose;g.B(z7,g.TF);g.h=z7.prototype;g.h.Xp=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Ae=function(a){this.la()||(a&&A7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){j7(this.M,a)};
g.h.lG=function(){return null};
g.h.aw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.aw("");z7.fa.X.call(this)};g.B(B7,z7);g.h=B7.prototype;g.h.Zv=function(a){if(this.o){if(this.o==a)return;A7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);iEa(this)};
g.h.rk=function(a){this.info("launchWithParams no-op for Cast: "+g.Hg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Ae()},this),(0,g.A)(function(){this.Ae(Error("Failed to stop receiver app."))},this)):this.Ae(Error("Stopping cast device witout session."))};
g.h.aw=g.z;g.h.X=function(){this.info("disposeInternal");g.jE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;B7.fa.X.call(this)};
g.h.LV=function(a,b){if(!this.la())if(b){var c=g.hx(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hg(c));switch(d){case "mdxSessionStatus":hEa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.h.Oz=function(a,b,c,d){eEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.hE((0,g.A)(this.Oz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.lG=function(){return this.o};
g.h.IX=function(a){this.la()||a||(A7(this,"Cast session died."),this.Ae())};g.B(C7,z7);g.h=C7.prototype;g.h.Zv=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.rk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.jE(this.F);this.C?this.C.stop((0,g.A)(this.Ae,this,null),(0,g.A)(this.Ae,this,"Failed to stop DIAL device.")):this.Ae()};
g.h.X=function(){this.o();this.o=g.z;g.jE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;C7.fa.X.call(this)};
g.h.LX=function(a){this.la()||a||(A7(this,"DIAL session died."),this.o(),this.o=g.z,this.Ae())};
g.h.Qt=function(a){this.K=p6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,kEa(this));a(b);jEa(this)}else this.G=(0,g.A)(function(){g.jE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,kEa(this));a(b);jEa(this)},this),this.F=g.hE((0,g.A)(function(){this.G()},this),100)};
g.h.BM=function(a,b,c){eEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Xp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Qt(b,c)},this),(0,g.A)(function(a){A7(this,"Failed to get DIAL screen: "+a);
this.Qt(b,c)},this))};g.B(D7,z7);D7.prototype.stop=function(){this.Ae()};
D7.prototype.Zv=g.z;D7.prototype.rk=function(){g.jE(this.o);this.o=window.NaN;var a=r6(this.J.ue(),this.A.label);a?this.Xp(a):this.Ae(Error("No such screen"))};
D7.prototype.X=function(){g.jE(this.o);this.o=window.NaN;D7.fa.X.call(this)};g.B(E7,g.TF);g.h=E7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.PD,this),(0,g.A)(this.pU,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.iS,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),SDa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.kG,this)),this.B=mEa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.gc("Failed to set initial custom receivers: "+g.Hg(a))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.A)(function(a){this.gc("Failed to initialize API: "+g.Hg(a));
b(!1)},this))};
g.h.zW=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.A.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=r6(this.A.ue(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=lEa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.gc("Failed to set initial custom receivers: "+g.Hg(a))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.A,d),!0)}this.o.aw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.h.AW=function(a){this.la()?this.gc("Setting connection data on disposed cast v2"):this.o?this.o.rk(a):this.gc("Setting connection data without a session")};
g.h.KX=function(){this.la()?this.gc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.PD,this),(0,g.A)(this.KU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.kG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Va(g.y("yt.mdx.remote.debug.handlers_")||[],PDa);g.jf(this.o);E7.fa.X.call(this)};
g.h.gc=function(a){j7("Controller",a)};
g.h.QD=function(a,b){this.o==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.lU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:H7(this,new B7(this.A,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.iS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.BM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Qt,b))};
g.h.PD=function(a){if(!this.la()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.A,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=r6(this.A.ue(),c.label);
d&&m6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.jf(this.o),this.o=new B7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.QD,this,this.o)),this.o.rk(null));this.o.Zv(a)}}};
g.h.JX=function(){return this.o?this.o.lG():null};
g.h.KU=function(a){this.la()||(this.gc("Failed to estabilish a session: "+g.Hg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.h.pU=function(a){F7("Receiver availability updated: "+a);if(!this.la()){var b=G7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.h.kG=function(){this.la()||(this.B=mEa(this),F7("Updating custom receivers: "+g.Hg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.gc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.AW;E7.prototype.setConnectedScreenStatus=E7.prototype.zW;E7.prototype.stopSession=E7.prototype.KX;E7.prototype.getCastSession=E7.prototype.JX;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.h=S7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.eg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.rb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+U7(this):this.J};
g.h.clone=function(){return new S7(Y7(this))};g.B($7,g.TF);g.h=$7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.pause)};
g.h.gG=function(a){if(1==this.o){if(this.A){var b=a8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.rb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.V("remotePlayerChange")}else b8(this,g.Fa(this.gG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.V("remotePlayerChange")}else b8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Fa(this.setVolume,a,b))};
g.h.gF=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Hg(b.style),g.hc(d,c.A));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Fa(this.gF,a,b))};
g.h.Qw=function(a,b){if(1==this.o){e8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Jb.id});var c=a8(this);c.audioTrackId=b.Jb.id;c8(this,c)}else b8(this,g.Fa(this.Qw,a,b))};
g.h.fG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Fa(this.fG,a,b))};
g.h.eG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Fa(this.eG,a,b))};
g.h.hz=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.hz)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}$7.fa.dispose.call(this)};
g.h.X=function(){zEa(this);this.C=null;this.D.clear();Z7(this,null);$7.fa.X.call(this)};
g.h.Rw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.AC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.gU=function(a,b){this.V(a,b)};
g.h.FR=function(a){if(!a)this.Pm(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.h.Pm=function(a){j7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),AEa(this),this.V("remotePlayerChange")};
g.h.ER=function(a){a?(AEa(this),this.V("remotePlayerChange")):this.Pm(null)};
g.h.RR=function(){var a=wEa();a&&Z7(this,a)};
g.h.gc=function(a){j7("CP",a)};g.B(g8,g.TF);g.h=g8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.v(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.v(k)&&(l.currentIndex=k);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=k||0;this.jb.state=3;V7(this.jb,m);this.C="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Hg(l));this.o.connect({method:"setPlaylist",
params:g.Hg(l)},a,WCa())}else h8("Connecting without params"),this.o.connect({},a,WCa());CEa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),i8(this,3));g8.fa.dispose.call(this)};
g.h.X=function(){j8(this);l8(this);k8(this);g.jE(this.J);this.J=window.NaN;g.jE(this.K);this.K=window.NaN;this.B=null;g.DF(this.T);this.T.length=0;this.o.dispose();g8.fa.X.call(this);this.C=this.G=this.A=this.jb=this.o=null};
g.h.QK=function(){this.F(2)};
g.h.JR=function(){h8("Channel opened");this.O&&(this.O=!1,k8(this),this.M=g.hE((0,g.A)(function(){h8("Timing out waiting for a screen.");this.F(1)},this),15E3));
$Ca(MDa(this.o),this.aa)};
g.h.GR=function(){h8("Channel closed");(0,window.isNaN)(this.D)?w6(!0):w6();this.dispose()};
g.h.HR=function(a){w6();(0,window.isNaN)(this.H())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,h8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),i8(this,2))};
g.h.IR=function(a){a.params?h8("Received: action="+a.action+", params="+g.Hg(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.hx(a.params.devices);this.A=(0,g.I)(a,function(a){return new k6(a)});
a=!!g.La(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
FEa(this,a);break;case "loungeScreenDisconnected":g.Wa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
FEa(this,!1);break;case "remoteConnected":var b=new k6(g.hx(a.params.device));g.La(this.A,function(a){return b?a.id==b.id:!1})||g.Sa(this.A,b);
break;case "remoteDisconnected":b=new k6(g.hx(a.params.device));g.Wa(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":HEa(this,a);break;case "nowPlaying":JEa(this,a);break;case "onStateChange":IEa(this,a);break;case "onAdStateChange":KEa(this,a);break;case "onVolumeChanged":LEa(this,a);break;case "onSubtitlesTrackChanged":GEa(this,a);break;case "nowAutoplaying":MEa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":NEa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.h.lW=function(){if(this.B){var a=this.B;this.B=null;this.jb.videoId!=a&&m8(this,"getNowPlaying")}};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.Xd;g8.prototype.ia=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?e7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
g8.prototype.getProxyState=g8.prototype.ia;g8.prototype.F=function(a){h8("Disconnecting with "+a);j8(this);this.V("beforeDisconnect",a);1==a&&w6();NDa(this.o,a);this.dispose()};
g8.prototype.disconnect=g8.prototype.F;g8.prototype.ha=function(){var a=this.jb;this.B&&(a=this.jb.clone(),X7(a,this.B,a.index));return Y7(a)};
g8.prototype.getPlayerContextData=g8.prototype.ha;
g8.prototype.na=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.B=b.videoId,g.jE(this.J),this.J=g.hE((0,g.A)(this.lW,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.o==b.o&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&W7(this.jb)==W7(b)&&g.Hg(this.jb.A)==g.Hg(b.A)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
g8.prototype.setPlayerContextData=g8.prototype.na;g8.prototype.Z=function(){var a=this.o.F.id,b=g.La(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
g8.prototype.getOtherConnectedRemoteId=g8.prototype.Z;g8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.G)():window.NaN};
g8.prototype.getReconnectTimeout=g8.prototype.H;g8.prototype.ba=function(){return this.C||"UNSUPPORTED"};
g8.prototype.getAutoplayMode=g8.prototype.ba;g8.prototype.da=function(){return this.G||""};
g8.prototype.getAutoplayVideoId=g8.prototype.da;g8.prototype.va=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.lu(a.o);a.start()}};
g8.prototype.reconnect=g8.prototype.va;g8.prototype.ka=function(a,b){m8(this,a,b);EEa(this)};
g8.prototype.sendMessage=g8.prototype.ka;g.B(n8,n7);g.h=n8.prototype;g.h.ue=function(a){return this.hd.$_gs(a)};
g.h.contains=function(a){return!!this.hd.$_c(a)};
g.h.get=function(a){return this.hd.$_g(a)};
g.h.start=function(){this.hd.$_st()};
g.h.add=function(a,b,c){this.hd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.hd.$_r(a,b,c)};
g.h.Uq=function(a,b,c,d){this.hd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.hd.$_ubk(this.A[a]);this.A.length=0;this.hd=null;n8.fa.X.call(this)};
g.h.GX=function(){this.V("screenChange")};
g.h.DT=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.HX;w7.prototype.$_gsppc=w7.prototype.jG;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Uq;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.ue;w7.prototype.$_gos=w7.prototype.iG;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Xd;var o8=null,p8=null,E8=null,t8=[];g.t(F8,g.M);g.h=F8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.C.stop();this.D.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.MD,this);this.o.unsubscribe("remotePlayerChange",this.Sm,this);this.o.unsubscribe("remoteQueueChange",this.Yp,this);this.o.unsubscribe("autoplayUpNext",this.iD,this);this.o.unsubscribe("previousNextChange",this.JD,this);this.o.unsubscribe("nowAutoplaying",this.AD,this);this.o.unsubscribe("autoplayDismissed",this.hD,this);this.o=this.H=null};
g.h.gC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(I8(this)){if(!a8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":a8(this.o).rb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Ql(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Qw(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();K8(this,0==c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Qw(this.A.getVideoData(1).videoId,c)}};
g.h.DR=function(a){this.L.LK(a)};
g.h.hX=function(a){this.gC("control_subtitles_set_track",g.$b(a)?null:a)};
g.h.vF=function(){var a=this.A.Bc("captions","track");g.$b(a)||J8(this,a)};
g.h.xD=function(a){if(I8(this)){this.o.unsubscribe("remotePlayerChange",this.Sm,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Sm,this)}};
g.h.YS=function(){g.$b(this.F)||ZEa(this,this.F);this.G=!1};
g.h.MD=function(a,b){this.D.stop();2==b&&this.sF()};
g.h.Sm=function(){if(I8(this)){this.C.stop();var a=a8(this.o);switch(a.o){case 1081:case 1:H8(this,new g.GP(8));this.rF();break;case 1085:case 3:H8(this,new g.GP(9));break;case 1083:case 0:H8(this,new g.GP(2));this.K.stop();G8(this,this.A.getVideoData().lengthSeconds);break;case 1084:H8(this,new g.GP(4));break;case 2:H8(this,new g.GP(4));G8(this,W7(a));break;case -1:H8(this,new g.GP(64));break;case -1E3:H8(this,new g.GP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
a8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,ZEa(this,a));a=a8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.RF()}else YEa(this)};
g.h.JD=function(){this.A.V("mdxpreviousnextchange")};
g.h.Yp=function(){I8(this)||YEa(this)};
g.h.PJ=function(){this.o.hz()};
g.h.iD=function(a){a&&(a=g.yE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.lV,this)}))&&(this.O=(0,g.A)(a.abort,a))};
g.h.lV=function(a,b){var c=new g.BO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.AD=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.hD=function(){this.A.V("mdxautoplaycanceled")};
g.h.IP=function(a,b){-1==a8(this.o).o?K8(this,a):b&&this.o.gG(a)};
g.h.RF=function(){if(I8(this)){var a=a8(this.o);this.B.Ga(this.T);a.muted?this.A.mute():this.A.mg();this.A.setVolume(a.volume);this.T=this.B.R(this.A,"onVolumeChange",this.xD)}};
g.h.rF=function(){this.C.stop();if(!this.o.la()){var a=a8(this.o);a.rb()&&H8(this,new g.GP(8));G8(this,W7(a));this.C.start()}};
g.h.sF=function(){this.D.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(L8,g.W);L8.prototype.D=function(a){aFa(this,a.state)};g.t(M8,g.CY);M8.prototype.L=function(){var a=this.B.Bc("remote","receivers");a&&1<a.length&&!this.B.Bc("remote","quickCast")?(this.J=g.lb(a,this.F,this),g.DY(this,(0,g.I)(a,this.F)),a=this.B.Bc("remote","currentReceiver"),this.Df(this.F(a)),this.enable(!0)):this.enable(!1)};
M8.prototype.F=function(a){return a.key};
M8.prototype.Cf=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
M8.prototype.Ad=function(a){g.CY.prototype.Ad.call(this,a);this.B.Rd("remote","currentReceiver",this.J[a]);this.D.Ob()};g.t(N8,g.GU);g.h=N8.prototype;g.h.create=function(){SEa(g.FM(g.Y(this.o)));this.F.push(g.eG("yt-remote-before-disconnect",this.yR,this));this.F.push(g.eG("yt-remote-connection-change",this.qU,this));this.F.push(g.eG("yt-remote-receiver-availability-change",this.KD,this));this.F.push(g.eG("yt-remote-auto-connect",this.oU,this));this.F.push(g.eG("yt-remote-receiver-resumed",this.nU,this));this.KD()};
g.h.load=function(){this.o.Ju();g.GU.prototype.load.call(this);this.D=new F8(this,this.o,this.A);var a=(a=XEa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!=a&&(this.J=a||0,this.o.V("progresssync",a,void 0));$Ea(this,this.G,this.G);g.M_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.kf(this.D,this.A);this.A=this.D=null;g.GU.prototype.unload.call(this);g.M_(this.o.app,5)};
g.h.X=function(){g.fG(this.F);g.GU.prototype.X.call(this)};
g.h.Fm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.gC.apply(this.D,[a].concat(g.oa(c)))};
g.h.GK=function(){return this.loaded?this.D.suggestion:null};
g.h.eg=function(){return this.A?a8(this.A).eg:!1};
g.h.hasNext=function(){return this.A?a8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.wP=function(){var a=a8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.jd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+U7(a):a.C,isPeggedToLive:1>=(a.F?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+U7(a):a.B,seekableStart:0<a.D?a.D+U7(a):a.D}};
g.h.xP=function(){this.A&&this.A.eG()};
g.h.yP=function(){this.A&&this.A.fG()};
g.h.yR=function(a){1==a&&(this.K=this.A?a8(this.A):null)};
g.h.qU=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.jf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.KB(a.videoId,W7(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.KD=function(){this.H=[this.B].concat(UEa());var a=z8()||this.B;O8(this,a);this.o.xa("onMdxReceiversChange")};
g.h.oU=function(){var a=z8();O8(this,a)};
g.h.nU=function(){this.C=z8()};
g.h.vP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Q7():O8(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&Q7(),!0):!1}};
g.h.zP=function(){e8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Nc=function(){return!1};g.CX.remote=N8;})(_yt_player);
